version: '2'
services:
  load_balancer:
    image: nginx_lb
    ports:
      - "80:8080"
  web1:
    image: simple_server
    volumes:
      - ./html1:/data/www
  web2:
    image: simple_server
    volumes:
      - ./html2:/data/www
 
