apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
  name: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-container
  template:
    metadata:
      labels:
        app: demo-container
    spec:
      containers:
        - name: main
          image: {{ .Values.image }}